### ISSUE TITLE
Direct download isnt working for Discord Canary.

### ISSUE THREAD

**Issue by Jeremy2131** [Inve1951/BetterDiscordStuff#8]
above :D

**Comment by Inve1951** [comment]
should be working. however there were changes to DOM and css which can cause the file tabs to be _invisible_.
here's a temporary fix by [DevilBro](https://github.com/mwittrien/BetterDiscordAddons):
```css
#files_directDownload {
    z-index: 1000 !important;
}
```
drop above code into _custom css_ in settings and hit `save` and `update`.

i'll address this when/if the changes make it to stable.
